const data = {
  0: {
    0: [
      [null, null, null, 8, 3, null, null, 5, 7],
      [null, null, 8, 5, null, null, 6, null, null],
      [1, 3, null, null, null, 2, null, 8, null],
      [8, null, 2, 3, 9, null, 7, null, null],
      [6, null, null, 1, null, null, null, 3, 2],
      [null, 5, 7, 2, null, 4, null, 9, null],
      [null, 6, null, 4, 1, null, 3, 7, null],
      [null, 7, 3, 9, null, 8, null, 6, null],
      [null, null, null, 7, 6, null, 4, null, null],
    ],
    1: [
      [8, null, null, 4, 7, 3, null, null, null],
      [null, 2, 6, 8, 5, 1, null, 9, null],
      [null, null, 5, null, null, null, 8, null, null],
      [null, 1, 3, null, null, 8, 4, null, null],
      [6, null, 7, 3, null, 2, 9, null, null],
      [null, 5, null, null, 9, 7, 6, null, 8],
      [null, 6, 2, 7, 3, null, 5, null, null],
      [null, 3, null, 2, null, null, 7, null, 6],
      [4, null, null, 6, null, null, null, 2, null],
    ],
  },
  1: {
    0: [
      [null, null, null, 3, 9, null, null, null, null],
      [null, 5, null, 6, null, null, null, null, 9],
      [null, 4, null, null, null, 2, null, 6, null],
      [null, null, 7, null, null, 5, null, 1, null],
      [null, null, 3, null, null, null, null, 9, null],
      [null, null, 8, null, 7, 3, null, null, 2],
      [null, null, 5, null, null, 6, 8, null, null],
      [null, null, null, null, null, null, null, null, null],
      [null, 1, null, null, null, 7, null, 2, null],
    ],
    1: [
      [null, 7, null, 2, 9, 6, null, null, 5],
      [null, null, null, null, 8, null, 7, null, null],
      [6, 5, null, null, null, null, null, null, null],
      [4, 6, null, null, 2, null, 5, 3, null],
      [null, null, null, 8, null, null, null, null, 9],
      [null, null, null, null, null, 4, null, 6, null],
      [null, 2, null, null, 5, null, 9, 1, null],
      [null, null, 9, null, 3, null, null, null, null],
      [null, null, null, 9, null, null, 2, 5, 4],
    ],
  },
  2: {
    0: [
      [null, 6, 5, 2, null, null, 4, null, null],
      [null, 7, null, null, null, null, 1, null, null],
      [null, 2, null, 4, null, null, null, null, 8],
      [null, null, null, null, null, null, null, 1, null],
      [null, null, null, 5, 9, null, 6, null, 7],
      [null, null, null, 3, null, null, null, 5, null],
      [null, null, null, null, null, 7, null, null, null],
      [5, null, 1, null, null, null, null, 2, null],
      [null, 4, 3, null, null, null, null, null, null],
    ],
  },
};
export default data;
